SKELETON_ALPINELINUX_ADD_TOOLCHAIN_DEPENDENCY = NO
SKELETON_ALPINELINUX_ADD_SKELETON_DEPENDENCY = NO
SKELETON_ALPINELINUX_INSTALL_STAGING = YES

SKELETON_ALPINELINUX_DEPENDENCIES = host-makedevs
SKELETON_ALPINELINUX_PROVIDES = skeleton
CUSTOM_ROOTFS_DIR="/tmp/alpine-rootfs"

define SKELETON_ALPINELINUX_BUILD_CMDS
	@if [ ! -d $(CUSTOM_ROOTFS_DIR) ]; then \
		echo "Error: $(CUSTOM_ROOTFS_DIR) does not exist. Please generate it manually for the desired architecture."; \
		exit 1; \
	fi
endef

define SKELETON_ALPINELINUX_INSTALL_TARGET_CMDS
	$(call SYSTEM_RSYNC,$(CUSTOM_ROOTFS_DIR),$(TARGET_DIR))
	$(call SYSTEM_BIN_SBIN_LIB_DIRS,$(TARGET_DIR))
	$(call SYSTEM_USR_SYMLINKS_OR_DIRS,$(TARGET_DIR))
	$(call SYSTEM_LIB_SYMLINK,$(TARGET_DIR))
endef

define SKELETON_ALPINELINUX_INSTALL_STAGING_CMDS
	$(call SYSTEM_RSYNC,$(CUSTOM_ROOTFS_DIR),$(STAGING_DIR))
	$(call SYSTEM_BIN_SBIN_LIB_DIRS,$(STAGING_DIR))
	$(call SYSTEM_USR_SYMLINKS_OR_DIRS,$(STAGING_DIR))
	$(call SYSTEM_LIB_SYMLINK,$(STAGING_DIR))
endef

$(eval $(generic-package))