services:
    ubuntu-buildroot:
        image: ubuntu-buildroot/frankoslaw:v1.0.3
        build:
            context: ./
            dockerfile: ./Dockerfile
        privileged: true
        stdin_open: true
        tty: true
        network_mode: host
        volumes:
            - ./:/root/buildroot-external
            - ../buildroot:/root/buildroot
            - ${HOME}/.buildroot-ccache:/root/.buildroot-ccache
        environment:
            BR2_EXTERNAL: "../buildroot-external"
