services:
  ubuntu-buildroot:
    image: ubuntu-buildroot/frankoslaw:v1.0.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/root/buildroot-external:z
      - ../buildroot:/root/buildroot:z
      - ../dts:/root/dts:z
