services:
  ubuntu-buildroot:
    image: ubuntu-buildroot/frankoslaw:v1.0.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/root/buildroot-external:z
      - ../buildroot:/root/buildroot:z
      - /tmp:/tmp:z
      - /var/run/docker.sock:/var/run/docker.sock:z
